Repository YAPP-Github/FullCar-Server, pull requests merged in 2024-01, with the labels that each got.

#3 feat: kakao social login
  .gitignore
  build.gradle
  src/main/java/com/fullcar/FullcarApplication.java
  src/main/java/com/fullcar/core/config/SecurityConfig.java
  src/main/java/com/fullcar/core/config/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/fullcar/core/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/fullcar/core/config/jwt/JwtExceptionType.java
  src/main/java/com/fullcar/core/config/jwt/JwtTokenProvider.java
  src/main/java/com/fullcar/core/config/jwt/UserAuthentication.java
  src/main/java/com/fullcar/core/exception/BadRequestException.java
  src/main/java/com/fullcar/core/exception/BaseException.java
  src/main/java/com/fullcar/core/exception/InternalServerException.java
  src/main/java/com/fullcar/core/exception/NotFoundException.java
  src/main/java/com/fullcar/core/exception/UnauthorizedException.java
  src/main/java/com/fullcar/core/response/ApiResponse.java
  src/main/java/com/fullcar/core/response/ErrorCode.java
  src/main/java/com/fullcar/core/response/SuccessCode.java
  src/main/java/com/fullcar/member/application/AppleAuthService.java
  src/main/java/com/fullcar/member/application/AuthService.java
  src/main/java/com/fullcar/member/application/AuthServiceProvider.java
  src/main/java/com/fullcar/member/application/KakaoAuthService.java
  src/main/java/com/fullcar/member/application/MemberService.java
  src/main/java/com/fullcar/member/domain/Member.java
  src/main/java/com/fullcar/member/domain/MemberId.java
  src/main/java/com/fullcar/member/domain/MemberIdService.java
  src/main/java/com/fullcar/member/domain/MemberRepository.java
  src/main/java/com/fullcar/member/domain/MemberSocialType.java
  src/main/java/com/fullcar/member/domain/SnowFlake.java
  src/main/java/com/fullcar/member/presentation/AuthController.java
  src/main/java/com/fullcar/member/presentation/MemberController.java
  src/main/java/com/fullcar/member/presentation/dto/KakaoInfoDto.java
  src/main/java/com/fullcar/member/presentation/dto/request/AuthRequestDto.java
  src/main/java/com/fullcar/member/presentation/dto/response/AuthResponseDto.java
Labels: feat, 🐲서경🐲

#9 feat: Swagger Configuration.
  build.gradle
  src/main/java/com/fullcar/core/config/SecurityConfig.java
  src/main/java/com/fullcar/core/config/SwaggerConfig.java
  src/main/resources/application.properties
Labels: feat, 영훈

#11 feat: Renew access token
  build.gradle
  src/main/java/com/fullcar/core/config/SecurityConfig.java
  src/main/java/com/fullcar/core/config/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/fullcar/core/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/fullcar/core/config/jwt/JwtTokenProvider.java
  src/main/java/com/fullcar/core/exception/CustomException.java
  src/main/java/com/fullcar/core/exception/CustomExceptionHandler.java
  src/main/java/com/fullcar/core/response/ApiResponse.java
  src/main/java/com/fullcar/core/response/ErrorCode.java
  src/main/java/com/fullcar/core/response/SuccessCode.java
  src/main/java/com/fullcar/member/application/AuthServiceProvider.java
  src/main/java/com/fullcar/member/domain/MemberRepository.java
  src/main/java/com/fullcar/member/presentation/AuthController.java
  src/main/java/com/fullcar/member/presentation/dto/request/AuthTokenRequestDto.java
  src/main/java/com/fullcar/member/presentation/dto/response/AuthTokenResponseDto.java
Labels: feat, 🐲서경🐲

#14 feat: connect swagger to auth APIs
  src/main/java/com/fullcar/member/application/AuthServiceProvider.java
  src/main/java/com/fullcar/member/presentation/AuthController.java
  src/main/java/com/fullcar/member/presentation/dto/request/AuthRequestDto.java
  src/main/java/com/fullcar/member/presentation/dto/request/AuthTokenRequestDto.java
  src/main/java/com/fullcar/member/presentation/dto/response/AuthResponseDto.java
  src/main/java/com/fullcar/member/presentation/dto/response/AuthTokenResponseDto.java
Labels: feat, 🐲서경🐲

#16 config: CI workflow
  .github/workflows/deploy.yml
  Dockerfile
Labels: feat, 🐲서경🐲

#18 fix: changed GET to POST on renew accessToken API
  src/main/java/com/fullcar/member/presentation/AuthController.java
Labels: bug, 🐲서경🐲

#20 feat: CD pipeline
  .github/workflows/deploy.yml
  appspec.yml
  scripts/deploy.sh
Labels: feat, 🐲서경🐲

#19 feat: Carpool Register API
  src/main/java/com/fullcar/carpool/application/CarpoolMapper.java
  src/main/java/com/fullcar/carpool/application/CarpoolService.java
  src/main/java/com/fullcar/carpool/domain/Carpool.java
  src/main/java/com/fullcar/carpool/domain/CarpoolId.java
  src/main/java/com/fullcar/carpool/domain/CarpoolRepository.java
  src/main/java/com/fullcar/carpool/domain/CarpoolState.java
  src/main/java/com/fullcar/carpool/domain/Cost.java
  src/main/java/com/fullcar/carpool/domain/Driver.java
  src/main/java/com/fullcar/carpool/domain/MoodType.java
  src/main/java/com/fullcar/carpool/domain/PeriodType.java
  src/main/java/com/fullcar/carpool/domain/service/CarpoolIdService.java
  src/main/java/com/fullcar/carpool/presentation/CarpoolController.java
  src/main/java/com/fullcar/carpool/presentation/dto/CarpoolDto.java
  src/main/java/com/fullcar/core/annotation/CurrentMember.java
  src/main/java/com/fullcar/core/config/SecurityConfig.java
  src/main/java/com/fullcar/core/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/fullcar/core/config/jwt/JwtTokenProvider.java
  src/main/java/com/fullcar/core/response/ErrorCode.java
  src/main/java/com/fullcar/core/response/SuccessCode.java
  src/main/java/com/fullcar/member/application/AuthServiceProvider.java
  src/main/java/com/fullcar/member/application/CustomUserDetailService.java
  src/main/java/com/fullcar/member/application/MemberService.java
  src/main/java/com/fullcar/member/domain/MemberId.java
  src/main/java/com/fullcar/member/domain/MemberRepository.java
  src/main/java/com/fullcar/member/presentation/dto/CustomUserDetails.java
Labels: feat, 영훈

#24 fix: CD pipeline
  .github/workflows/deploy.yml
Labels: feat, 🐲서경🐲

#29 del: gender, ageRange field in the member domain
  src/main/java/com/fullcar/member/application/auth/KakaoAuthService.java
  src/main/java/com/fullcar/member/domain/member/Member.java
  src/main/java/com/fullcar/member/presentation/auth/dto/KakaoInfoDto.java
Labels: feat, 🐲서경🐲

#31 feat: Carpool list API
  src/main/java/com/fullcar/carpool/application/CarpoolMapper.java
  src/main/java/com/fullcar/carpool/application/CarpoolService.java
  src/main/java/com/fullcar/carpool/domain/CarpoolRepository.java
  src/main/java/com/fullcar/carpool/presentation/CarpoolController.java
  src/main/java/com/fullcar/carpool/presentation/dto/request/CarpoolRequestDto.java
  src/main/java/com/fullcar/carpool/presentation/dto/response/CarpoolResponseDto.java
  src/main/java/com/fullcar/core/response/SuccessCode.java
Labels: feat, 영훈

#36 feat: Carpool detail API
  src/main/java/com/fullcar/carpool/application/CarpoolMapper.java
  src/main/java/com/fullcar/carpool/application/CarpoolService.java
  src/main/java/com/fullcar/carpool/domain/Driver.java
  src/main/java/com/fullcar/carpool/presentation/CarpoolController.java
  src/main/java/com/fullcar/carpool/presentation/dto/request/CarpoolRequestDto.java
  src/main/java/com/fullcar/carpool/presentation/dto/response/CarpoolResponseDto.java
  src/main/java/com/fullcar/core/response/ErrorCode.java
  src/main/java/com/fullcar/member/domain/car/Car.java
  src/main/java/com/fullcar/member/domain/car/CarRepository.java
  src/main/java/com/fullcar/member/domain/member/Member.java
Labels: feat, 영훈
