Repository YAPP-Github/FullCar-Server, pull requests merged in 2024-02, with the labels that each got.

#40 feat: get member's information API
  src/main/java/com/fullcar/member/application/member/MemberMapper.java
  src/main/java/com/fullcar/member/application/member/MemberService.java
  src/main/java/com/fullcar/member/presentation/member/MemberController.java
  src/main/java/com/fullcar/member/presentation/member/dto/response/MemberGetResponseDto.java
Labels: feat, 🐲서경🐲

#43 Feat: Sending an authentication email to user
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/fullcar/core/response/ErrorCode.java
  src/main/java/com/fullcar/core/response/SuccessCode.java
  src/main/java/com/fullcar/member/application/member/MemberMapper.java
  src/main/java/com/fullcar/member/domain/blacklist/Blacklist.java
  src/main/java/com/fullcar/member/domain/blacklist/BlacklistId.java
  src/main/java/com/fullcar/member/domain/blacklist/BlacklistRepository.java
  src/main/java/com/fullcar/member/domain/blacklist/service/BlacklistIdService.java
  src/main/java/com/fullcar/member/domain/member/service/MailService.java
  src/main/java/com/fullcar/member/infra/EmailMessage.java
  src/main/java/com/fullcar/member/infra/MailClient.java
  src/main/java/com/fullcar/member/presentation/member/MemberController.java
  src/main/java/com/fullcar/member/presentation/member/dto/request/EmailRequestDto.java
  src/main/resources/static/images/fullcar_logo.png
  src/main/resources/templates/email.html
Labels: feat, 🐲서경🐲

#47 del: onboarding Flag from social login API
  src/main/java/com/fullcar/member/application/auth/AuthServiceProvider.java
  src/main/java/com/fullcar/member/domain/member/Member.java
  src/main/java/com/fullcar/member/presentation/auth/dto/response/AuthResponseDto.java
Labels: 🐲서경🐲, refactor

#49 feat: Sent form list API
  src/main/java/com/fullcar/carpool/application/form/FormService.java
  src/main/java/com/fullcar/carpool/domain/carpool/Carpool.java
  src/main/java/com/fullcar/carpool/domain/form/FormRepository.java
  src/main/java/com/fullcar/carpool/presentation/form/FormController.java
  src/main/java/com/fullcar/core/response/ErrorCode.java
Labels: feat, 영훈

#51 feat: onboarding API
  src/main/java/com/fullcar/member/application/member/CompanyMapper.java
  src/main/java/com/fullcar/member/application/member/MemberMapper.java
  src/main/java/com/fullcar/member/application/member/MemberService.java
  src/main/java/com/fullcar/member/domain/member/Member.java
  src/main/java/com/fullcar/member/presentation/member/MemberController.java
  src/main/java/com/fullcar/member/presentation/member/dto/request/OnboardingRequestDto.java
Labels: feat, 🐲서경🐲

#56 feat: nickname duplication check API
  src/main/java/com/fullcar/core/response/ErrorCode.java
  src/main/java/com/fullcar/core/response/SuccessCode.java
  src/main/java/com/fullcar/member/application/member/MemberService.java
  src/main/java/com/fullcar/member/domain/member/MemberRepository.java
  src/main/java/com/fullcar/member/presentation/member/MemberController.java
  src/main/java/com/fullcar/member/presentation/member/dto/request/NicknameRequestDto.java
  src/main/java/com/fullcar/member/presentation/member/dto/response/NicknameResponseDto.java
Labels: feat, 🐲서경🐲

#58 feat: social logout API
  src/main/java/com/fullcar/core/response/SuccessCode.java
  src/main/java/com/fullcar/member/application/auth/AuthServiceProvider.java
  src/main/java/com/fullcar/member/domain/member/Member.java
  src/main/java/com/fullcar/member/presentation/auth/AuthController.java
Labels: feat, 🐲서경🐲

#60 feat: update car information API
  src/main/java/com/fullcar/core/response/ErrorCode.java
  src/main/java/com/fullcar/core/response/SuccessCode.java
  src/main/java/com/fullcar/member/application/car/CarMapper.java
  src/main/java/com/fullcar/member/application/car/CarService.java
  src/main/java/com/fullcar/member/domain/car/Car.java
  src/main/java/com/fullcar/member/domain/member/Member.java
  src/main/java/com/fullcar/member/domain/member/MemberRepository.java
  src/main/java/com/fullcar/member/presentation/car/CarController.java
  src/main/java/com/fullcar/member/presentation/car/dto/request/CarRequestDto.java
  src/main/java/com/fullcar/member/presentation/car/dto/response/CarResponseDto.java
Labels: feat, 🐲서경🐲

#61 feat: Received form list API
  src/main/java/com/fullcar/carpool/application/form/FormService.java
  src/main/java/com/fullcar/carpool/domain/form/FormRepository.java
  src/main/java/com/fullcar/carpool/presentation/form/FormController.java
Labels: feat, 영훈

#64 feat: Sent form detail API
  src/main/java/com/fullcar/carpool/application/carpool/CarpoolMapper.java
  src/main/java/com/fullcar/carpool/application/carpool/CarpoolService.java
  src/main/java/com/fullcar/carpool/application/form/FormMapper.java
  src/main/java/com/fullcar/carpool/application/form/FormService.java
  src/main/java/com/fullcar/carpool/domain/form/Form.java
  src/main/java/com/fullcar/carpool/domain/form/FormRepository.java
  src/main/java/com/fullcar/carpool/presentation/carpool/CarpoolController.java
  src/main/java/com/fullcar/carpool/presentation/carpool/dto/response/CarpoolResponseDto.java
  src/main/java/com/fullcar/carpool/presentation/form/FormController.java
  src/main/java/com/fullcar/carpool/presentation/form/dto/response/FormResponseDto.java
  src/main/java/com/fullcar/core/response/ErrorCode.java
Labels: feat, 영훈

#66 feat: Received form detail API
  src/main/java/com/fullcar/carpool/application/form/FormService.java
  src/main/java/com/fullcar/carpool/presentation/form/FormController.java
Labels: feat, 영훈

#71 feat: Form acceptance, reject API
  src/main/java/com/fullcar/carpool/application/form/FormService.java
  src/main/java/com/fullcar/carpool/domain/form/Form.java
  src/main/java/com/fullcar/carpool/domain/form/ResultMessage.java
  src/main/java/com/fullcar/carpool/presentation/form/FormController.java
  src/main/java/com/fullcar/carpool/presentation/form/dto/request/FormUpdateDto.java
  src/main/java/com/fullcar/carpool/presentation/form/dto/response/FormResponseDto.java
  src/main/java/com/fullcar/core/response/ErrorCode.java
Labels: feat, 영훈

#76 feat: add a random authentication code in mail feature
  src/main/java/com/fullcar/core/response/ErrorCode.java
  src/main/java/com/fullcar/member/application/mail/MailMapper.java
  src/main/java/com/fullcar/member/application/member/MemberMapper.java
  src/main/java/com/fullcar/member/domain/mail/Mail.java
  src/main/java/com/fullcar/member/domain/mail/MailId.java
  src/main/java/com/fullcar/member/domain/mail/MailRepository.java
  src/main/java/com/fullcar/member/domain/mail/service/MailIdService.java
  src/main/java/com/fullcar/member/domain/member/service/MailService.java
  src/main/java/com/fullcar/member/infra/MailClient.java
  src/main/java/com/fullcar/member/presentation/member/MemberController.java
  src/main/resources/templates/email.html
Labels: feat, 🐲서경🐲

#81 fix: get member API
  src/main/java/com/fullcar/member/application/member/MemberMapper.java
Labels: bug, 🐲서경🐲

#83 feat: My carpool list API
  src/main/java/com/fullcar/carpool/application/carpool/CarpoolMapper.java
  src/main/java/com/fullcar/carpool/application/carpool/CarpoolService.java
  src/main/java/com/fullcar/carpool/domain/carpool/CarpoolRepository.java
  src/main/java/com/fullcar/carpool/presentation/carpool/CarpoolController.java
  src/main/java/com/fullcar/carpool/presentation/carpool/dto/response/MyCarpoolDto.java
Labels: feat, 영훈

#86 add: onBoarding responseDto to post onBoarding API
  src/main/java/com/fullcar/core/exception/CustomExceptionHandler.java
  src/main/java/com/fullcar/member/application/member/MemberMapper.java
  src/main/java/com/fullcar/member/application/member/MemberService.java
  src/main/java/com/fullcar/member/domain/member/Member.java
  src/main/java/com/fullcar/member/presentation/member/MemberController.java
  src/main/java/com/fullcar/member/presentation/member/dto/request/OnBoardingRequestDto.java
  src/main/java/com/fullcar/member/presentation/member/dto/response/OnBoardingResponseDto.java
Labels: feat, 🐲서경🐲

#89 fix: social login & withdraw member
  src/main/java/com/fullcar/core/exception/CustomExceptionHandler.java
  src/main/java/com/fullcar/core/response/ErrorCode.java
  src/main/java/com/fullcar/member/application/auth/AppleAuthService.java
  src/main/java/com/fullcar/member/application/auth/AuthService.java
  src/main/java/com/fullcar/member/application/auth/AuthServiceProvider.java
  src/main/java/com/fullcar/member/application/auth/KakaoAuthService.java
  src/main/java/com/fullcar/member/application/member/MemberMapper.java
  src/main/java/com/fullcar/member/domain/mail/MailRepository.java
  src/main/java/com/fullcar/member/domain/member/Member.java
  src/main/java/com/fullcar/member/domain/member/SocialType.java
  src/main/java/com/fullcar/member/infra/MailClient.java
  src/main/java/com/fullcar/member/presentation/auth/AuthController.java
  src/main/java/com/fullcar/member/presentation/auth/dto/request/WithdrawRequestDto.java
  src/main/java/com/fullcar/member/presentation/auth/dto/response/AppleAuthTokenResponseDto.java
Labels: bug, 🐲서경🐲

#90 feat: Carpool close API
  src/main/java/com/fullcar/carpool/application/carpool/CarpoolService.java
  src/main/java/com/fullcar/carpool/application/form/FormService.java
  src/main/java/com/fullcar/carpool/domain/carpool/Carpool.java
  src/main/java/com/fullcar/carpool/domain/form/Form.java
  src/main/java/com/fullcar/carpool/domain/form/FormMessage.java
  src/main/java/com/fullcar/carpool/domain/form/FormRepository.java
  src/main/java/com/fullcar/carpool/domain/form/event/FormStateChangedEvent.java
  src/main/java/com/fullcar/carpool/domain/service/NotificationService.java
  src/main/java/com/fullcar/carpool/infra/NotificationClient.java
  src/main/java/com/fullcar/carpool/infra/dto/NotificationDto.java
  src/main/java/com/fullcar/carpool/infra/event/NotificationEvent.java
  src/main/java/com/fullcar/carpool/infra/event/NotificationEventListener.java
  src/main/java/com/fullcar/carpool/presentation/carpool/CarpoolController.java
  src/main/java/com/fullcar/core/response/ErrorCode.java
Labels: feat, 영훈

#96 fix: separate saving device token API from social login API
  src/main/java/com/fullcar/core/response/SuccessCode.java
  src/main/java/com/fullcar/member/application/auth/AppleAuthService.java
  src/main/java/com/fullcar/member/application/auth/KakaoAuthService.java
  src/main/java/com/fullcar/member/application/member/MemberMapper.java
  src/main/java/com/fullcar/member/application/member/MemberService.java
  src/main/java/com/fullcar/member/domain/member/Member.java
  src/main/java/com/fullcar/member/presentation/auth/dto/request/AppleAuthRequestDto.java
  src/main/java/com/fullcar/member/presentation/auth/dto/request/KakaoAuthRequestDto.java
  src/main/java/com/fullcar/member/presentation/member/MemberController.java
  src/main/java/com/fullcar/member/presentation/member/dto/request/DeviceTokenRequestDto.java
  src/main/java/com/fullcar/member/presentation/member/dto/response/DeviceTokenResponseDto.java
Labels: bug, 🐲서경🐲

#98 fix: kakao withdraw
  src/main/java/com/fullcar/member/application/auth/KakaoAuthService.java
  src/main/java/com/fullcar/member/domain/auth/SocialId.java
Labels: bug, 🐲서경🐲

#99 feat: Carpool delete API
  src/main/java/com/fullcar/carpool/application/carpool/CarpoolService.java
  src/main/java/com/fullcar/carpool/application/form/CarpoolClosedEventHandler.java
  src/main/java/com/fullcar/carpool/application/form/CarpoolDeletedEventHandler.java
  src/main/java/com/fullcar/carpool/application/form/FormMapper.java
  src/main/java/com/fullcar/carpool/application/form/FormService.java
  src/main/java/com/fullcar/carpool/application/form/FormStateChangedEventHandler.java
  src/main/java/com/fullcar/carpool/domain/carpool/Carpool.java
  src/main/java/com/fullcar/carpool/domain/carpool/event/CarpoolClosedEvent.java
  src/main/java/com/fullcar/carpool/domain/carpool/event/CarpoolDeletedEvent.java
  src/main/java/com/fullcar/carpool/domain/form/Form.java
  src/main/java/com/fullcar/carpool/domain/form/event/FormStateChangedEvent.java
  src/main/java/com/fullcar/carpool/infra/NotificationClient.java
  src/main/java/com/fullcar/carpool/infra/dto/NotificationDto.java
  src/main/java/com/fullcar/carpool/infra/event/NotificationEvent.java
  src/main/java/com/fullcar/carpool/infra/event/NotificationEventListener.java
  src/main/java/com/fullcar/carpool/presentation/carpool/CarpoolController.java
  src/main/java/com/fullcar/core/response/ErrorCode.java
  src/main/java/com/fullcar/core/response/SuccessCode.java
Labels: feat, 영훈

#102 fix: Revise Carpool, Form list dto
  src/main/java/com/fullcar/carpool/application/carpool/CarpoolService.java
  src/main/java/com/fullcar/carpool/application/form/FormService.java
  src/main/java/com/fullcar/carpool/presentation/carpool/CarpoolController.java
Labels: bug, 영훈
